### Registration using Email
POST localhost:8080/api/v1/article/admin
Content-Type: application/json

{
  "title": "Article title 1",
  "description": "Article 1 description",
  "content": "Article 1 content",
  "imageId": "12345",
  "regionId": 1,
  "readTime": 60,
  "categoryList": [
    {
      "id": 1
    },
    {
      "id": 2
    }
  ],
  "sectionList": [
    {
      "id": 1
    },
    {
      "id": 2
    }
  ]
}
