### GET ALL
GET localhost:8080/category/v1

### CREATE
POST localhost:8080/category/v1
Content-Type: application/json

{
  "orderNumber": 2,
  "nameUz": "Iqtisodiyot",
  "nameRu": "Экономика",
  "nameEn": "Economics",
  "key": "iqtisodiyot"
}

### UPDATE
PUT localhost:8080/category/v1/3
Content-Type: application/json

{
  "orderNumber": 3,
  "nameUz": "Iqtisodiyot",
  "nameRu": "Экономика",
  "nameEn": "Economics",
  "visible": true,
  "key": "iqtisodiyot",
  "createDate": "2025-05-18T12:00:00"
}

### DELETE
DELETE localhost:8080/category/v1/2
Content-Type: application/json

### GET BY Language
GET localhost:8080/category/v1/English
Content-Type: application/json


