### GET ALL
GET localhost:8080/profile/paginationList?password=11042000&size=2&page=1

### CREATE
POST localhost:8080/profile
Content-Type: application/json

{
  "name": "Eshmat6",
  "surname": "Boltayev6",
  "username": "EshBolta6",
  "password": "123456789",
  "roles": ["ROLE_PUBLISHER", "ROLE_USER"],
  "visible": true
}

### UPDATE
PUT localhost:8080/profile/updateByUser?username=AhmadSodiq&password=11042000
Content-Type: application/json

{
  "name": "MirzaAhmad",
  "surname": "Sodiqov",
  "username": "AhmadSodiq",
  "password": "11042000",
  "roles": ["ROLE_ADMIN", "ROLE_USER"],
  "visible": true
}


### UPDATE
PUT localhost:8080/profile/updateByAdmin?username=AhmadSodiq&password=11042000
Content-Type: application/json

{
  "name": "Eshmat1",
  "surname": "Boltayev1",
  "username": "EshBolta1",
  "password": "3456789",
  "roles": ["ROLE_MODERATOR", "ROLE_USER"],
  "visible": true
}

### Delete
DELETE localhost:8080/profile/delete?userId=4&username=AhmadSodiq&password=11042000

### GET BY FILTER
GET localhost:8080/profile/filter?page=1&size=8
Content-Type: application/json

{
  "name": "Eshmat"
}

### GET BY LANG
GET localhost:8080/pr



