### GET ALL
GET localhost:8080/region/v1

### CREATE
POST localhost:8080/region/v1
Content-Type: application/json

{
  "nameUz": "ANDIJON",
  "nameRu": "КАРАКАЛПАКИСТАН",
  "nameEn": "KARAKALPAKISTAN",
  "createDate": "2025-05-20T12:00:00",
  "key": "QORAQALPOG'ISTON",
  "visible": true,
  "orderNumber": 3
}

### UPDATE
PUT localhost:8080/region/v1/2
Content-Type: application/json

{
  "nameUz": "TOSHKENT",
  "nameRu": "ТАШКЕНТ",
  "nameEn": "TASHKENT",
  "createDate": "2025-05-19T12:00:00",
  "key": "tashkent",
  "visible": true,
  "orderNumber": 1
}


### DELETE
DELETE localhost:8080/region/v1/5
Content-Type: application/json

### GET BY Language
GET localhost:8080/region/v1/byLanguage
Accept-Language: EN

