### GET ALL
GET localhost:8080/region/v1

### CREATE
POST localhost:8080/region/v1
Content-Type: application/json

{
  "nameUz": "FARGONA",
  "nameRu": "ФЕРГАНА",
  "nameEn": "FERGANA",
  "key": "fergana",
  "orderNumber": 2
}

### UPDATE
PUT localhost:8080/region/v1/2
Content-Type: application/json

{
  "nameUz": "TOSHKENT",
  "nameRu": "ТАШКЕНТ",
  "nameEn": "TASHKENT"
}


### DELETE
DELETE localhost:8080/region/v1/5
Content-Type: application/json

### GET BY Language
GET localhost:8080/region/v1/byLanguage
Accept-Language: EN

