package dasturlash.uz.enums;

public enum RegionNameEn {
    BUKHARA, SAMARKAND, FERGANA, ANDIJAN, SIRDARYA, SURKHANDARYA, TASHKENT, KARAKALPAKISTAN, NAMANGAN, KASHKADARYA, NAVAI, KHAREZM, JIZZAKH

}
